### PR TITLE
Fix up GPT partition tables automatically

### LINKED ISSUE #4974: Support 4k storage
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

VMs not working/starting right from a fresh install.

**Brief summary**

Right after a fresh install, all VMs fail to mount root and therefore fails to start beyond the point where they expect /dev/xvda3 available. This happens on a device that has 4kB logical and physical block sizes (NVMe drive). This was not problem in R3.2 (as it used files by default for VM storage).

**To Reproduce**

1. Install Qubes to a drive with 4kB sector size (both logical / physical); (I put /boot to a SATA drive with 512B sectors to avoid BIOS/NVMe boot challenges, rest of the system is on the NVMe with 4kB sectors).
2. Firstboot stuff fails
3. After clicking "finish" for firstboot, find out that no VM will start successfully (which explains firstboot failures I guess)
4. Look to the VM logs, and find this from there:

```...
[    0.887548] blkfront: xvda: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    0.902355] blkfront: xvdb: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    0.924386] blkfront: xvdc: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    0.940325] blkfront: xvdd: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
Waiting for /dev/xvda* devices...
Qubes: Doing R/W setup for TemplateVM...
[    1.049451] random: sfdisk: uninitialized urandom read (4 bytes read)
[    1.052481]  xvdc: xvdc1
[    1.060250] random: mkswap: uninitialized urandom read (16 bytes read)
Setting up swapspace version 1, size = 8 GiB (8589930496 bytes)
no label, UUID=...
Qubes: done.
mount: wrong fs type, bad option, bad superblock on /dev/xvda,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Waiting for /dev/xvdd device...
mount: /dev/xvdd is write-protected, mounting read-only
[    1.099814] EXT4-fs (xvdd): mounting ext3 file system using the ext4 subsystem
[    1.106796] EXT4-fs (xvdd): mounted filesystem with ordered data mode. Opts: (null)
mount: /sysroot not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
[    1.119049] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x1e335a008d5, max_idle_ns: 440795216613 ns
mount: /sysroot not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
switch_root: failed to mount moving /sysroot to /: Invalid argument
switch_root: failed. Sorry.
[    1.217841] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
...
```

**Expected behavior**

VMs would start. Firstboot stuff would work. Drives with 4kB sector size would work.

**Additional context**

I've tracked this down to the handling of the partition table. With 512B sectors the location of the GPT differs from that of with 4kB sectors and therefore VMs fail to find the correct partition table from xvda. Obviously also the partition start/end values will be off by the factor of 8 because the templates are built(?) with an assumption of 512B sector size.

I'm not sure if there are other assumptions based on 512B sectors with the other /dev/xvd* drives.

**Solutions you've tried**

I cloned a template and I tried to manually fix the partition table of the clone (in dom0 through /dev/qubes_dom0/...). There's was plenty of space before the first partition, however, at the end the drive is so tight on space that the GPT secondary table won't fit so the xvda3 partition's tail was truncated slightly and I didn't try to resize its filesystem first (this probably causes some problems, potentially corruption?). With such a fixed partition table, I could start VMs (but there are then some other problems/oddities that might be due to incomplete firstboot or non-fixed fedora template, I only fixed the debian one which I mainly use normally). I could possibly enlarge the relevant LV slightly to avoid the truncate problem at the tail of xvda3 but I've not tried that yet.

I tried to look if I could somehow force pv/vg/lv chain to fake the logical sector size but couldn't find anything from the manpages.

Libvirt *might* be able to fake the ```logical_block_size``` but I've not yet tried that.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

During install, I used the custom install steps to create manual partitioning (but I think it is irrelevant).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None I could find, some other issues included failure to mount root successfully but the causes are different.

**Decided solution**

Add a partition table conversion to initramfs. Specifically, write a tool that would check if partition table matches current block size. If it matches, do nothing. If not, convert it to the right block size format before mounting anything. And destroy the wrong partition table (if isn't directly overridden by the converted one) to prevent confusion which one is the current one.

References:
https://github.com/QubesOS/qubes-issues/issues/4974#issuecomment-482897265
https://github.com/QubesOS/qubes-issues/issues/4974#issuecomment-1677356693

### PR DESCRIPTION
**Pull request by DemiMarie**
This has many problems:

- [x] Old partition tables are not cleared before writing the partition table entry that would overwrite them.
- [x] An invalid partition table header is not written before the partition table entries that the valid one would refer to.
- [x] A valid partition table header is written before the entries it refers to, not after.
- [x] CRC32 checksums are ~~not checked when reading (but are created when writing).~~ are now always checked.
- [x] Lots and lots of debug prints.
- [x] No tests (it does pass a local test, though).
- [x] No installation (so this file would not even be included in a built package!).
- [x] The fixer is recompiled even when there is no need to rebuild it.
- [x] The default CFLAGS are meant for local development & debugging.
- [x] `NDEBUG` is forcibly undefined.

Fixes: QubesOS/qubes-issues#4974

### CODE REVIEW

**Comment by marmarek** [comment]
This fails to build on several distributions due to `cc1: error: unrecognized command-line option ...-std=c23...`

File: gptfixer/gpt.c [hunk 1]
```diff
@@ -0,0 +1,914 @@
...
+static bool check_mbr(struct Mbr *mbr, uint64_t size_in_sectors) {
+  bool changed = false;
+  if (mbr->signature[0] != 0x55 || mbr->signature[1] != 0xAA) {
+    errx(1,
+         "Invalid MBR signature: expected 0x55 0xAA, got 0x%02" PRIX8
+         " 0x%02" PRIX8,
+         mbr->signature[0], mbr->signature[1]);
+  }
+  if (mbr->partition_record[0].os_type != 0xEE) {
+    errx(1, "Bad protective MBR: OS type is not GPT Protective");
```
Comment (marmarek) [inline gptfixer/gpt.c]: This depends on how it's going to be integrated, but it isn't necessarily an error. It may mean there is intentionally no MBR in which case this program should exit not doing anything.

File: gptfixer/gpt.c [hunk 2]
```diff
@@ -0,0 +1,914 @@
...
+  }
+  struct MbrPartitionRecord first_partition = {0};
+  for (int i = 2; i <= 4; ++i) {
```
Comment (marmarek) [inline gptfixer/gpt.c]: It's uncommon to have loop iterator for an array 1-based (and then -1 when using it). Any specific reason for it?

File: gptfixer/gpt.c [hunk 3]
```diff
@@ -0,0 +1,914 @@
...
+  uint32_t const expected_size_in_lba =
+      (uint32_t)(size_in_sectors - 1 > UINT32_MAX ? UINT32_MAX
+                                                  : size_in_sectors - 1);
+  if (size_in_lba != expected_size_in_lba) {
+    warnx(
+        "Bad protective MBR: does not cover whole disk: size in LBA is %" PRIu32
+        ", expected %" PRIu32,
+        size_in_lba, expected_size_in_lba);
+    /* TODO: big endian */
+    memcpy(mbr->partition_record[0].size_in_lba, &expected_size_in_lba, 4);
```
Comment (marmarek) [inline gptfixer/gpt.c]: and changed = true?

File: gptfixer/gpt.c [hunk 4]
```diff
@@ -0,0 +1,914 @@
...
+  }
+  uint64_t bytes_required =
+      (uint64_t)gpt->header.SizeOfPartitionEntry * (uint64_t)gpt->used_entries;
+  uint64_t sectors_required =
+      (bytes_required + (uint64_t)(sector_size - 1)) / sector_size;
+  if (sectors - 2 < sectors_required) {
+    // This should only happen with tiny disks.
+    errx(1, "Cannot fit new partition table into disk space");
+  }
+  bytes_required = (sectors_required + 2) * sector_size;
```
Comment (marmarek) [inline gptfixer/gpt.c]: This could use a comment what all those 1 and 2 are.

File: gptfixer/gpt.c [hunk 5]
```diff
@@ -0,0 +1,914 @@
...
+static void write_and_free_gpt(int fd, struct GPT *gpt, uint32_t sector_size,
+                               uint64_t size) {
+  if (size == 0)
+    abort();
+  void *entries = gpt->entries;
+  assert(entries != NULL);
+  gpt->used_entries = 0;
+  gpt->entries = NULL;
+  ssize_t res =
+      pwrite64(fd, gpt, sector_size, (off_t)(gpt->header.MyLBA * sector_size));
```
Comment (marmarek) [inline gptfixer/gpt.c]:
```suggestion
      pwrite64(fd, &gpt->header, sector_size, (off_t)(gpt->header.MyLBA * sector_size));
```
?

File: gptfixer/gpt.c [hunk 6]
```diff
@@ -0,0 +1,914 @@
...
+  if (read == -1) {
+    err(1, "Error reading partition table");
+  }
+
+  if (read != (ssize_t)needed) {
+    errx(1, "Expected to read %" PRIu64 " bytes, but only got %zd bytes",
+         partition_table_bytes, read);
+  }
+
+  struct GPT *gpt = (struct GPT *)header;
```
Comment (marmarek) [inline gptfixer/gpt.c]:
```suggestion
  struct GPT *gpt = (struct GPT *)header_buffer;
```
?

File: gptfixer/gpt.c [hunk 7]
```diff
@@ -0,0 +1,914 @@
...
+        entry->EndingLBA, entry->Attributes);
+  }
+}
+
+int main(int argc, char **argv) {
+  if (argc != 2)
+    errx(1, "Usage: fixgpt BLOCK_DEVICE");
+
+  const char *dev = argv[1];
+  if (0 && (strncmp(dev, "/dev/xvd", 8) != 0 || strchr(dev + 8, '/') != NULL))
```
Comment (marmarek) [inline gptfixer/gpt.c]: I know it's disabled, but I don't think it's a good idea to even have this later. This tool shouldn't care about device path (for example it should very well work on /dev/sda if somebody disables xen-blkfront).

File: gptfixer/gpt.c [hunk 8]
```diff
@@ -0,0 +1,914 @@
...
+  if (fsync(fd)) {
+    err(1, "fsync(\"%s\")", argv[1]);
+  }
+  {
+    char *buffer = aligned_alloc(sector_size, sector_size);
+    if (pread(fd, buffer, sector_size, 0) != sector_size) {
+      err(1, "Failed reading MBR from block device or short read");
+    }
+    static_assert(sizeof(struct Mbr) <= 512, "Bad MBR size");
+    check_mbr((struct Mbr *)buffer, sectors);
```
Comment (marmarek) [inline gptfixer/gpt.c]: What about return value? If it's changed I think you need to write it back, no?

File: gptfixer/gpt.c [hunk 9]
```diff
@@ -0,0 +1,914 @@
...
+  }
+
+  struct GPT *gpt = read_and_check_gpt(fd, 1, sector_size, sectors);
+  if (gpt == NULL) {
+    gpt = read_and_check_gpt(fd, sectors - 1, sector_size, sectors);
+  }
+  bool try_changing = gpt == NULL;
+  if (try_changing) {
+    uint32_t new_sector_size = (sector_size == 4096) ? 512 : 4096;
+    uint64_t new_sectors =
```
Comment (marmarek) [inline gptfixer/gpt.c]: Those are actually old sectors and sector size, no?

File: gptfixer/gpt.c [hunk 10]
```diff
@@ -0,0 +1,914 @@
...
+    // "First, do no harm": always start by overwriting the GPT we
+    // did *not* use, so there is always at least one good GPT!
+    struct GPT *new_gpt;
+    uint64_t to_write = 0;
+    if (new_sector_size < sector_size) {
+      new_gpt = gpt_grow_sectors(used_primary ? sectors - 1 : 1, sector_size,
+                                 new_sector_size, sectors, gpt, &to_write);
+    } else {
+      new_gpt = gpt_shrink_sectors(used_primary ? sectors - 1 : 1, sector_size,
+                                   new_sector_size, sectors, gpt, &to_write);
```
Comment (marmarek) [inline gptfixer/gpt.c]: Take location of the other GPT from the header, instead of hardcoding to `sectors - 1` - otherwise it will explode on first boot after resizing disk (if that happens to be also first boot on a disk with different sector size). Same in few other locations below.
(don't try to adjust GPT size to the actual disk size - leave that to the OS)

File: gptfixer/gpt.c [hunk 11]
```diff
@@ -0,0 +1,914 @@
...
+  } else {
+    print_gpts(gpt);
+  }
+  free(gpt->entries);
+  free(gpt);
+  close(fd);
+  fflush(NULL);
+  if (ferror(stdout))
+    err(1, "Write error on stdout");
+}
```
Comment (marmarek) [inline gptfixer/gpt.c:1085]: Missing return 0.

**Review by marmarek — CHANGES_REQUESTED** [review]
I've read the older version, and after you pushed b3e1f4d6e6d76a8c9c71d9a7e71c67755ac528dd, I've removed comments you addressed already (before me posting them ;) ).

File: gptfixer/gpt.c (hunk 8 above)
Comment (marmarek) [reply gptfixer/gpt.c]: And also, I think the protective MBR should be verified against the size from GPT, to not mess it up in case of disk resize.

File: gptfixer/gpt.c (hunk 2 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: The purpose is to provide 1-based user-facing error messages, as “partition 0” would be confusing.

File: gptfixer/gpt.c (hunk 8 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: The code now unconditionally writes back a pMBR if it made any changes to the GPT.  This is necessary when going from 512 to 4096, as there is no other way to atomically clobber the old GPT header.

File: gptfixer/gpt.c (hunk 9 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: Fixed.

File: gptfixer/gpt.c (hunk 10 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: The backup GPT is only looked at if the primary GPT is invalid.  If the primary GPT is valid, the backup GPT is written before the primary GPT is.  Since a GPT cannot be written atomically, this requires that the backup GPT must be written at the end of the disk, so that if there is a problem (such as power failure) either the backup GPT is now valid (at the new sector size) or the old primary GPT (with the old sector size) is still present.  Furthermore, writing a GPT will clobber any other GPTs at the same end of the disk, so if the primary GPT was used the backup GPT must be written first and visa versa.  Therefore, adjusting the GPT size to the actual disk size is unavoidable, unless I am missing something.

Comment (marmarek) [reply gptfixer/gpt.c]: > The backup GPT is only looked at if the primary GPT is invalid.

That's not true. At the very least, fdisk will complain if backup GPT doesn't match the primary GPT even if primary GPT is valid.

Anyway, I'm not going to argue about this too much, it's a very rare case anyway (resizing the disk and changing sector size at the same time). Just ensure you don't resize GPT if you don't change sector size (I think this case is okay currently).

File: gptfixer/gpt.c (hunk 2 above)
Comment (marmarek) [reply gptfixer/gpt.c]: You know you can use `i+1` when formatting the message, right?
Right now you do `i-1` every time just to avoid doing `i+1` in case of unlikely error.
I know compiler will optimize this anyway, but the current version is at least unintuitive.

File: gptfixer/gpt.c [hunk 12]
```diff
@@ -0,0 +1,786 @@
+#ifdef NDEBUG
+#undef NDEBUG // FOR DEVELOPMENT ONLY!!!!
+#endif
+#ifndef _GNU_SOURCE
+#define _GNU_SOURCE
+#endif
+#pragma GCC diagnostic error "-Wall"
+#pragma GCC diagnostic error "-Wextra"
+#pragma GCC diagnostic error "-Wpadded"
+#pragma GCC diagnostic error "-Wconversion"
```
Comment (marmarek) [inline gptfixer/gpt.c]: Don't. The first two you added to CFLAGS already, if you really want the other two too, put them into the makefile. Do not take away control over compiler flags from the compiler call.

File: gptfixer/gpt.c [hunk 13]
```diff
@@ -0,0 +1,786 @@
...
+#include <unistd.h>
+
+#include <zlib.h>
+
+#include <assert.h>
+#if defined NDEBUG
+#define CHECK(x) ((void)((x) ? 0 : (abort(), 0)))
+#else
+#define CHECK assert
+#endif
```
Comment (marmarek) [inline gptfixer/gpt.c]: How many times do I need to repeat: do not try to bypass disabling asserts. Here you invented yet another method to keep them even if somebody defines `NDEBUG`, by open-coding `assert()`. Just don't.
For normal error checking (things that can happen in normal use) don't use asserts (regardless if development or production build). And for sanity checks you can use `assert()` and if somebody wishes to disable it, let them to.
Note I do not request to set `NDEBUG` in release build and never did. But it doesn't mean it should be ignored if somebody sets it.

I'll comment below on few uses of CHECK to which category they belong, but do review and adjust all of them.

File: gptfixer/gpt.c [hunk 14]
```diff
@@ -0,0 +1,786 @@
...
+    // Add sector_size once for backup GPT header.
+    uint64_t start_of_backup_gpt_table = size - (bytes_required + sector_size);
+    if (last_end_byte_offset > start_of_backup_gpt_table) {
+        errx(1,
+             "Cannot construct new GPT: Partition %" PRIu32 " ends at byte offset 0x%" PRIX64
+             ", but partition table uses space after 0x%" PRIX64,
+             partition_that_ends_last + 1, last_end_byte_offset, start_of_backup_gpt_table);
+    }
+    uint64_t first_usable_byte;
+    CHECK(!__builtin_mul_overflow(gpt->header.FirstUsableLBA, old_sector_size, &first_usable_byte));
```
Comment (marmarek) [inline gptfixer/gpt.c]: Technically, this should be proper error check, with a message about too large FirstUsableLBA value (aka invalid GPT). Alternatively, you could check FirstUsableLBA against the number of sectors on the disk - to get more meaningful error message, but I don't think you have `old_sectors` anywhere already?

File: gptfixer/gpt.c [hunk 15]
```diff
@@ -0,0 +1,786 @@
...
+        if (!unused_entry(entry)) {
+            uint64_t start_byte_offset = entry->StartingLBA * old_sector_size;
+            uint64_t end_byte_offset = (entry->EndingLBA + 1) * old_sector_size;
+            new_entry->StartingLBA = start_byte_offset / sector_size;
+            new_entry->EndingLBA = end_byte_offset / sector_size - 1;
+        }
+    }
+    *allocated = bytes_required;
+    fixup_gpt(new_gpt, bytes_required);
+    CHECK(new_gpt->entries);
```
Comment (marmarek) [inline gptfixer/gpt.c]: This, if anything, should be an assert, as you do have proper error checking for this earlier already.

File: gptfixer/gpt.c [hunk 16]
```diff
@@ -0,0 +1,786 @@
...
+        err(1, "fsync() failed");
+}
+
+static void create_new_gpt(int fd, bool used_primary, uint64_t sectors, uint32_t sector_size, uint32_t new_sector_size,
+                           struct GPT *gpt) {
+    struct GPT *new_gpt;
+    uint64_t to_write = 0;
+    new_gpt =
+        gpt_adjust_sectors(!used_primary ? sectors - 1 : 1, sector_size, new_sector_size, sectors, gpt, &to_write);
+    CHECK(new_gpt->entries);
```
Comment (marmarek) [inline gptfixer/gpt.c]: Again, an assert

File: gptfixer/gpt.c [hunk 17]
```diff
@@ -0,0 +1,786 @@
...
+    CHECK(length <= SSIZE_MAX);
+    CHECK((off_t)offset >= 0);
+    CHECK((uint64_t)(off_t)offset == offset);
+
+    ssize_t res = pwrite64(fd, data, (size_t)length, (off_t)offset);
+    CHECK(res >= -1);
+    if (res == -1)
+        err(1, "write error");
+    CHECK((size_t)res <= length);
+    if ((size_t)res != length)
```
Comment (marmarek) [inline gptfixer/gpt.c]: Those two CHECK actually make the code harder to follow. `rest == -1` and `res != length` already handle the actual error cases. Asserts for kernel/glibc code (as those CHECK are) make one think if there aren't any real error cases here

**Review by marmarek — CHANGES_REQUESTED** [review]

File: gptfixer/gpt.c (hunk 12 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: Gotcha — in the future I will rip these out before submitting them.

File: gptfixer/gpt.c [hunk 18]
```diff
@@ -0,0 +1,837 @@
...
+
+static struct GPT *gpt_adjust_sectors(uint64_t sector_offset, uint32_t sector_size, uint32_t old_sector_size,
+                                      uint64_t sectors, struct GPT *gpt, uint64_t *allocated) {
+    assert(sectors >= 6);
+    assert(valid_sector_size(old_sector_size));
+    assert(valid_sector_size(sector_size));
+    assert(sector_offset == 1 || sector_offset == sectors - 1);
+
+    uint64_t const size = sector_size * sectors;
+    struct GPT *new_gpt = aligned_alloc(sector_size, sector_size);
```
Comment (marmarek) [inline gptfixer/gpt.c]: A generic comment to all aligned_alloc calls: do you actually need those buffers to be sector-aligned? I don't think you use any API that requires such alignment.

File: dracut/full-dmroot/qubes_cow_setup.sh [hunk 19]
```diff
@@ -54,6 +54,9 @@ modprobe xenblk || modprobe xen-blkfront || warn "Qubes: Cannot load Xen Block F
 
 log_begin "Waiting for /dev/xvda* devices..."
 udevadm settle --exit-if-exists=/dev/xvda
+/usr/sbin/gptfix /dev/xvda
```
Comment (marmarek) [inline dracut/full-dmroot/qubes_cow_setup.sh]: Reload partition table afterwards? Or is it done implicitly already?

File: dracut/full-dmroot/qubes_cow_setup.sh [hunk 20]
```diff
@@ -54,6 +54,9 @@ modprobe xenblk || modprobe xen-blkfront || warn "Qubes: Cannot load Xen Block F
...
+udevadm settle --exit-if-exists=/dev/xvdb
+/usr/sbin/gptfix /dev/xvdb
```
Comment (marmarek) [inline dracut/full-dmroot/qubes_cow_setup.sh]: Normally xvdb isn't supposed to have partition table, so an error message from this tool is expected (and may confuse the user). Make sure the message in this case isn't too alarming.

And also, ensure it's always clear what a given message is about. Maybe add some message before calling the tool? Or ensure all messages have proper prefix (currently some of them have, but not all).

File: dracut/simple/init.sh [hunk 21]
```diff
@@ -28,6 +28,10 @@ die() {
 
 echo "Waiting for /dev/xvda* devices..."
 while ! [ -e /dev/xvda ]; do sleep 0.1; done
+# Fix up partition tables
+/usr/sbin/fixgpt /dev/xvda
+while ! [ -e /dev/xvdb ]; do sleep 0.1; done
+/usr/sbin/fixgpt /dev/xvdb
```
Comment (marmarek) [inline dracut/simple/init.sh]: Same comment as above.

File: dracut/full-dmroot/qubes_cow_setup.sh (hunk 19 above)
Comment (DemiMarie) [reply dracut/full-dmroot/qubes_cow_setup.sh]: Partition tables are reloaded by calling `BLKRRPART`.

File: dracut/full-dmroot/qubes_cow_setup.sh (hunk 20 above)
Comment (DemiMarie) [reply dracut/full-dmroot/qubes_cow_setup.sh]: I will drop this as it not only makes no sense but is a potential security problem.

**Comment by marmarek** [comment]
(the current version fails to build)

File: gptfixer/gpt.c (hunk 10 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: This may be a corner case, but it is still a case I want to handle correctly.  Can you explain, in detail, how this could go wrong?

My understanding is:

- Tools must create a primary and backup GPT.
- Tools must accept a primary GPT that is valid, even if the backup GPT is invalid.
- Tools must use the primary GPT if it is valid.
- If the primary GPT is valid but the backup GPT is invalid or visa versa, tools must not reject the GPT altogether but are allowed to issue a warning.

Do real-world tools behave differently than this?

File: gptfixer/gpt.c (hunk 18 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: Originally the code used direct I/O, which does require alignment.  I switched to buffered I/O later because `O_SYNC` actually provided the semantics I need and because I might need to read 512 bytes from a 4096-byte-sector device.

**Comment by DemiMarie** [comment]
This is now ready for review, and I recommend backporting to R4.2 if possible.  It’s a rather large change, but the bug it fixes is somewhat embarrassing.

**Comment by marmarek** [comment]
Debian 12 HVM fails to start with in-vm kernel (with no sector change needed):
```
[2024-11-20 16:36:03] [2J[3J[-1;-1ffixgpt: Sector size is 512, device size is 0x500000000, 0x2800000 sectors

[2024-11-20 16:36:03] Partition table is 16384 bytes long

[2024-11-20 16:36:03] Partition table entries consume 16384 bytes

[2024-11-20 16:36:03] Setting up swapspace version 1, size = 1073737728 bytes

[2024-11-20 16:36:03] UUID=a1448fb4-6ee4-44f2-b7b4-9a8dbc392229

[2024-11-20 16:36:03] mount: mounting /dev/mapper/dmroot on /root failed: No such file or directory

[2024-11-20 16:36:03] Failed to mount /dev/mapper/dmroot as root file system.

[2024-11-20 16:36:04] 
[2024-11-20 16:36:04] 
[2024-11-20 16:36:04] BusyBox v1.35.0 (Debian 1:1.35.0-4+b3) built-in shell (ash)
[2024-11-20 16:36:04] Enter 'help' for a list of built-in commands.
[2024-11-20 16:36:04] 
[2024-11-20 16:36:04] (initramfs) [6n[2024-11-20 16:38:14] Logfile Opened
```

**Comment by marmarek** [comment]
(and one log line got junk prefix)

**Comment by marmarek** [comment]
> (and one log line got junk prefix)

I don't see how that would be from this tool, maybe that's still from grub cleaning up terminal settings.

**Comment by marmarek** [comment]
And it looks like dom0-provided initramfs lacks the fixgpt binary:
```
/init: line 32: /usr/sbin/fixgpt: not found
```

**Comment by marmarek** [comment]
Another test iteration, this time Debian 12 HVM worked, but Debian 12 PV and Fedora 40 PVH failed:
```
[2024-11-22 01:36:34] [    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.11.8-200.fc40.x86_64 root=/dev/mapper/dmroot ro root=/dev/mapper/dmroot console=tty0 console=hvc0 swiotlb=8192 noresume clocksource=tsc xen_scrub_pages=0
...
[2024-11-22 01:36:37] [    3.210251] blkfront: xvda: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled; bounce buffer: enabled
[2024-11-22 01:36:37] [    3.231226]  xvda: xvda1 xvda2 xvda3
[2024-11-22 01:36:37] [    3.250629] blkfront: xvdb: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled; bounce buffer: enabled
[2024-11-22 01:36:37] [    3.267314] blkfront: xvdc: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled; bounce buffer: enabled
[2024-11-22 01:36:37] [    3.177537] dracut-pre-trigger[411]: gptfix: Sector size is 512, device size is 0x500000000, 0x2800000 sectors
[2024-11-22 01:36:37] [    3.394376]  xvda: xvda1 xvda2 xvda3
[2024-11-22 01:36:37] [    3.409244]  xvda: xvda1 xvda2 xvda3
[2024-11-22 01:36:37] [    3.711063]  xvdc: xvdc1 xvdc3
[2024-11-22 01:36:37] [    3.766307] Adding 1048572k swap on /dev/xvdc1.  Priority:-2 extents:1 across:1048572k SS
...
[2024-11-22 01:36:38] [[0;32m  OK  [0m] Finished [0;1;39msystemd-fsck-root.service[0m…System Check on /dev/mapper/dmroot.


[2024-11-22 01:36:38]          Mounting [0;1;39msysroot.mount[0m - /sysroot...


[2024-11-22 01:36:38] [    4.438454] EXT4-fs (xvda): VFS: Can't find ext4 filesystem
[2024-11-22 01:36:38] [    4.446723] EXT4-fs (xvda): VFS: Can't find ext4 filesystem
[2024-11-22 01:36:38] [    4.454289] EXT4-fs (xvda): VFS: Can't find ext4 filesystem
[2024-11-22 01:36:38] [[0;1;31mFAILED[0m] Failed to mount [0;1;39msysroot.mount[0m - /sysroot.


[2024-11-22 01:36:38] See 'systemctl status sysroot.mount' for details.
```

Looking at `dracut/full-dmroot/qubes_cow_setup.sh`, could it be maybe some race condition causing `[ -b /dev/xvda1 ]` test to fail  (udev being in process of re-creating partition devices)?
I guess similar thing might have happened to Debian 12 HVM before.

**Comment by marmarek** [comment]
And also, even though GPT didn't need changes here, I see reloading partition table, twice. Lets fix it last, as having this issue makes it easier to debug the other one.

**Comment by marmarek** [comment]
Just to not forget - there are a bunch of `fixup!` commits in the history here, to be squashed before merge. And TBH, this whole thing may want squashing to much smaller number of commits, especially since it is a candidate for backport.

**Comment by DemiMarie** [comment]
@marmarek: can you retest the most recent push?  It should fix all of the race conditions, though it loses a couple features (and so is not suitable for merging).

File: dracut/full-dmroot/qubes_cow_setup.sh [hunk 22]
```diff
@@ -54,20 +54,18 @@ modprobe xenblk || modprobe xen-blkfront || warn "Qubes: Cannot load Xen Block F
...
-        ROOT_DEV=${ROOT_DEV##*/}
-    else
-        ROOT_DEV=xvda3
-    fi
+# Fix up partition tables
+if /usr/sbin/gptfix fix /dev/xvda; then
+    udevadm settle --exit-if-exists=/dev/xvda3
+    ROOT_DEV=xvda3
+elif [ "$?" -ne 8 ]; then
+    die 'Invalid partition table that cannot be fixed'
```
Comment (marmarek) [inline dracut/full-dmroot/qubes_cow_setup.sh]: I think I did asked to not interrupt the boot if the tool doesn't know what to do...

**Comment by marmarek** [comment]
This time I tried actual conversion. I took a system installed with 512 block size and started it with block size 4096. After adjusting dom0 stuff manually, all VMs seems to have started successfully. I tested version as of https://github.com/QubesOS/qubes-linux-utils/commit/485c457215051a659e7db28d8f74fc12927370ef
But during conversion I've got several warnings(?):
```
[2024-11-22 21:48:05] Waiting for /dev/xvda* devices...
[2024-11-22 21:48:05] gptfix: Bad protective MBR: does not cover whole disk: size in LBA is 41943039, expected 5242879
[2024-11-22 21:48:05] gptfix: Sector size is 4096, device size is 0x500000000, 0x500000 sectors
[2024-11-22 21:48:05] gptfix: Wrong GPT signature
[2024-11-22 21:48:05] gptfix: Wrong GPT signature
[2024-11-22 21:48:05] Partition table is 16384 bytes long
[2024-11-22 21:48:05] Partition table entries consume 16384 bytes
[2024-11-22 21:48:05] gptfix: Found GPT with different sector size, altering
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0x100000, 0xC900000)
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0xC900000, 0xCB00000)
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0xCB00000, 0x4FFF00000)
[2024-11-22 21:48:05] LBA is 0x4FFFFF, Alternate LBA is 0x1, allocating 0x4000 bytes
[2024-11-22 21:48:05] Partition table is 16384 bytes long
[2024-11-22 21:48:05] GPT Partition Table Header:
[2024-11-22 21:48:05] Revision:                 0x00010000
[2024-11-22 21:48:05] HeaderSize:               92
[2024-11-22 21:48:05] HeaderCRC32:              537615431
[2024-11-22 21:48:05] Reserved:                 0
[2024-11-22 21:48:05] MyLBA:                    5242879
[2024-11-22 21:48:05] AlternateLBA:             1
[2024-11-22 21:48:05] FirstUsableLBA:           256
[2024-11-22 21:48:05] LastUsableLBA:            5242874
[2024-11-22 21:48:05] DiskGUID[16]:             2a6a79f4-77e3-bd45-b539-d6d49e569055
[2024-11-22 21:48:05] PartitionEntryLBA:        5242875
[2024-11-22 21:48:05] NumberOfPartitionEntries: 128
[2024-11-22 21:48:05] SizeOfPartitionEntry:     128
[2024-11-22 21:48:05] PartitionEntryArrayCRC32: 1571220439
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        28732ac1-1ff8-d211-ba4b-00a0c93ec93b
[2024-11-22 21:48:05] UniquePartitionGUID:      29654dfa-da56-c747-ae88-e2dfecb72621
[2024-11-22 21:48:05] StartingLBA:              0x100
[2024-11-22 21:48:05] EndingLBA:                0xc8ff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        48616821-4964-6f6e-744e-656564454649
[2024-11-22 21:48:05] UniquePartitionGUID:      b49d6c1e-911e-c446-846a-2030dcb13b8c
[2024-11-22 21:48:05] StartingLBA:              0xc900
[2024-11-22 21:48:05] EndingLBA:                0xcaff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        af3dc60f-8384-7247-8e79-3d69d8477de4
[2024-11-22 21:48:05] UniquePartitionGUID:      e6443269-073e-bf47-ad79-acade4293fe7
[2024-11-22 21:48:05] StartingLBA:              0xcb00
[2024-11-22 21:48:05] EndingLBA:                0x4ffeff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0x100000, 0xC900000)
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0xC900000, 0xCB00000)
[2024-11-22 21:48:05] gptfix: Partition consumes bytes [0xCB00000, 0x4FFF00000)
[2024-11-22 21:48:05] LBA is 0x1, Alternate LBA is 0x4FFFFF, allocating 0x4000 bytes
[2024-11-22 21:48:05] Partition table is 16384 bytes long
[2024-11-22 21:48:05] GPT Partition Table Header:
[2024-11-22 21:48:05] Revision:                 0x00010000
[2024-11-22 21:48:05] HeaderSize:               92
[2024-11-22 21:48:05] HeaderCRC32:              2173448561
[2024-11-22 21:48:05] Reserved:                 0
[2024-11-22 21:48:05] MyLBA:                    1
[2024-11-22 21:48:05] AlternateLBA:             5242879
[2024-11-22 21:48:05] FirstUsableLBA:           256
[2024-11-22 21:48:05] LastUsableLBA:            5242874
[2024-11-22 21:48:05] DiskGUID[16]:             2a6a79f4-77e3-bd45-b539-d6d49e569055
[2024-11-22 21:48:05] PartitionEntryLBA:        2
[2024-11-22 21:48:05] NumberOfPartitionEntries: 128
[2024-11-22 21:48:05] SizeOfPartitionEntry:     128
[2024-11-22 21:48:05] PartitionEntryArrayCRC32: 1571220439
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        28732ac1-1ff8-d211-ba4b-00a0c93ec93b
[2024-11-22 21:48:05] UniquePartitionGUID:      29654dfa-da56-c747-ae88-e2dfecb72621
[2024-11-22 21:48:05] StartingLBA:              0x100
[2024-11-22 21:48:05] EndingLBA:                0xc8ff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        48616821-4964-6f6e-744e-656564454649
[2024-11-22 21:48:05] UniquePartitionGUID:      b49d6c1e-911e-c446-846a-2030dcb13b8c
[2024-11-22 21:48:05] StartingLBA:              0xc900
[2024-11-22 21:48:05] EndingLBA:                0xcaff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] GPT Partition Table Entry:
[2024-11-22 21:48:05] PartitionTypeGUID:        af3dc60f-8384-7247-8e79-3d69d8477de4
[2024-11-22 21:48:05] UniquePartitionGUID:      e6443269-073e-bf47-ad79-acade4293fe7
[2024-11-22 21:48:05] StartingLBA:              0xcb00
[2024-11-22 21:48:05] EndingLBA:                0x4ffeff
[2024-11-22 21:48:05] Attributes:               0x0000000000000000
[2024-11-22 21:48:05] [    2.152297]  xvda: xvda1 xvda2 xvda3
```
(full output for completeness, but I'm talking about the initial few lines)

File: dracut/full-dmroot/qubes_cow_setup.sh (hunk 22 above)
Comment (DemiMarie) [reply dracut/full-dmroot/qubes_cow_setup.sh]: I’m fine with removing this `die` before merging, but I’d prefer to keep it while testing.  If this `die` is reached, it indicates a bug and the test should fail.

File: gptfixer/gpt.c (hunk 10 above)
Comment (DemiMarie) [reply gptfixer/gpt.c]: > Take location of the other GPT from the header, instead of hardcoding to `sectors - 1` - otherwise it will explode on first boot after resizing disk (if that happens to be also first boot on a disk with different sector size). Same in few other locations below.

Do you mean that if the primary GPT _header_ is valid, but the primary GPT _entries_ are invalid, the backup GPT _header_ should be read from `AlternateLBA` in the primary header?

Most of the places where `sectors - 1` is written refer to either:

1. Where to _write_ the backup GPT.  The backup GPT is meant as a backup if the primary GPT is bad, so it needs to be written at the well-known location regardless of where the primary GPT is.
2. Where to find the backup GPT if the primary GPT is bad.  In this case (such as if e.g. the primary header CRC32 checksum is invalid), there is no point (that I can think of) in using the primary GPT header’s `AlternateLBA` at all, as it’s presumably garbage.

Comment (DemiMarie) [reply gptfixer/gpt.c]: > (don't try to adjust GPT size to the actual disk size - leave that to the OS)

Ah, `qubes-rootfs-resize.service`.  That could also use this tool to find the partition to resize, instead of hardcoding 3 (but if you want to hardcode 3, that’s fine too).

**Comment by marmarek** [comment]
> Perhaps this macro should be removed?  It now expands to three nested
for loops...

Honestly, I was wondering when this will bite you :P It incidentally worked with `continue`, but not with `break`. Yes, nested loops in this kind of macro is a bad idea. If you need some extra variables, just let the user of the macro declare them and give them via macro parameters.

And another thing - I don't like extending the scope of this tool at all. I know having all that already, adding "just one more thing" is easy, but it was supposed to be a _small_ tool that does just one thing and does it well. Searching for specific partition is already questionable and takes about 10% of the code. So, to avoid endless stream of extending the scope, or even polishing the current extra features (like https://github.com/QubesOS/qubes-linux-utils/pull/119/commits/63979ea50f5d655663a494b9116e3c3c5fbeac8a), lets step back. Please limit the tool to _only_ fixing the partition table if necessary and remove everything else. Yes, this includes also "tidy" mode and searching for specific partition. You may keep the "check" mode (although more logical and possibly more useful thing would be "dry mode" which does everything except writing changed GPT back to the disk). From the init script point of view, you need exit code that distinguishes between those cases:
- no valid GPT found (may be corrupted, may be filesystem directly - doesn't matter)
- valid GPT found and it doesn't need conversion
- GPT found and it got converted to the current sector size (arguably the same as the earlier one from the script point of view)
- GPT found and needs conversion but cannot be converted for any reason, or some other error occurred

The tool can define more exit codes if really needed and useful, but please keep it reasonably simple. For example distinction between "no GPT found" and "no MBR found" is not useful from the script point of view (it may be useful for the human reading the log, but for that a message is sufficient).

**Comment by DemiMarie** [comment]
> * no valid GPT found (may be corrupted, may be filesystem directly - doesn't matter)

Does it really not matter?  If the GPT is corrupt then this would cause the wrapper script to mount an ext4 filesystem at a wrong offset, which is a really bad idea (it will interpret arbitrary on-disk data as filesystem metadata).  I can check for the 0xAA55 marker to see if there is a partition table or not: partitioned devices will have it, others won’t.

> searching for specific partition

Is it reasonable to hard-code `/dev/xvda3` in the wrapper script, at least for R4.3?  `qubes-rootfs-resize.service` already does that, so other partition numbers were never supported anyway.

**Comment by marmarek** [comment]
> Does it really not matter? If the GPT is corrupt then this would cause the wrapper script to mount an ext4 filesystem at a wrong offset, which is a really bad idea (it will interpret arbitrary on-disk data as filesystem metadata). I can check for the 0xAA55 marker to see if there is a partition table or not: partitioned devices will have it, others won’t.

Don't bother, not in scope of this PR. As I said, the scope of the tool is to fix sector size of GPT if it can. Not a generic partition detection/manipulation/whatever tool.

> Is it reasonable to hard-code `/dev/xvda3` in the wrapper script, at least for R4.3? `qubes-rootfs-resize.service` already does that, so other partition numbers were never supported anyway.

No. The script here is provided by dom0 and is supposed to work with any template. Some templates may have different partition layout (and then have modified resize rootfs script, or even not support rootfs resizing at all).
And again - focus on sector size, not other "improvements" to the init script or other parts. In fact, do drop https://github.com/QubesOS/qubes-linux-utils/pull/119/commits/94bbf5fc9d6a3bff70407374dbfddeee2ce123f4 from this PR (may be a candidate for a follow-up PR).

**Comment by DemiMarie** [comment]
> > Does it really not matter? If the GPT is corrupt then this would cause the wrapper script to mount an ext4 filesystem at a wrong offset, which is a really bad idea (it will interpret arbitrary on-disk data as filesystem metadata). I can check for the 0xAA55 marker to see if there is a partition table or not: partitioned devices will have it, others won’t.
> 
> Don't bother, not in scope of this PR. As I said, the scope of the tool is to fix sector size of GPT if it can. Not a generic partition detection/manipulation/whatever tool.

Ah, so the purpose is to make the minimum possible change, not to replace crufty shell scripts with nice C code?  I would like to do the latter as well at some point, but a PR that is being backported probably isn’t the place for that.

Also, is it really best to have the same exit code in both cases, instead of relying on the wrapper script to deal with that?  The wrapper script can trivially treat two different exit codes the same way, but not the same exit code two different ways.

> > Perhaps this macro should be removed?  It now expands to three nested
> > for loops...
> 
> Honestly, I was wondering when this will bite you :P It incidentally worked with `continue`, but not with `break`. Yes, nested loops in this kind of macro is a bad idea. If you need some extra variables, just let the user of the macro declare them and give them via macro parameters.

For what it is worth, I believe the Linux kernel is considering moving in the opposite direction, because using the user-provided variable after the loop leads to hard-to-catch bugs.

**Comment by marmarek** [comment]
> Also, is it really best to have the same exit code in both cases, instead of relying on the wrapper script to deal with that? The wrapper script can trivially treat two different exit codes the same way, but not the same exit code two different ways.

Yes, the wrapper can treat different codes as the same. But you wanted to extend the tool with extra handling for various cases that are not really relevant for the sector resize and this I'm opposing.

**Comment by DemiMarie** [comment]
> > Also, is it really best to have the same exit code in both cases, instead of relying on the wrapper script to deal with that? The wrapper script can trivially treat two different exit codes the same way, but not the same exit code two different ways.
> 
> Yes, the wrapper can treat different codes as the same. But you wanted to extend the tool with extra handling for various cases that are not really relevant for the sector resize and this I'm opposing.

Ah, I see.  There isn’t actually any “extra handling” I can think of, as the difference is just which number is passed to `errx()`.

File: dracut/simple/init.sh [hunk 23]
```diff
@@ -28,6 +28,9 @@ die() {
 
 echo "Waiting for /dev/xvda* devices..."
 while ! [ -e /dev/xvda ]; do sleep 0.1; done
+# Fix up partition tables
+/usr/sbin/gptfix /dev/xvda
+while ! [ -e /dev/xvda1 ]; do sleep 0.01; done
```
Comment (marmarek) [inline dracut/simple/init.sh]: This will sleep forever for non-partitioned device.

**Comment by marmarek** [comment]
```
[2024-11-25 07:19:13] [    3.296151] dracut-pre-trigger[414]: /usr/sbin/gptfix: Usage:
[2024-11-25 07:19:13] [    3.296323] dracut-pre-trigger[414]: /usr/sbin/gptfix:  gptfix [OPTIONS] [--] [check|fix] block-device-path
[2024-11-25 07:19:13] [    3.296419] dracut-pre-trigger[414]: /usr/sbin/gptfix:
[2024-11-25 07:19:13] [    3.296541] dracut-pre-trigger[414]: /usr/sbin/gptfix: Options:
[2024-11-25 07:19:13] [    3.296644] dracut-pre-trigger[414]: /usr/sbin/gptfix: --unsafe-skip-bpb-check              Do not check for a BIOS Parameter Block (BPB) before making changes.
[2024-11-25 07:19:13] [    3.296766] dracut-pre-trigger[414]: /usr/sbin/gptfix:                                      WARNING: in some (EXTREMELY rare) cases, this can corrupt a
[2024-11-25 07:19:13] [    3.296863] dracut-pre-trigger[414]: /usr/sbin/gptfix:                                      FAT or NTFS file system that happens to have a valid GPT.
[2024-11-25 07:19:13] [    3.296978] dracut-pre-trigger[414]: /usr/sbin/gptfix: --verbose                            Log a bunch of messages to stderr.
[2024-11-25 07:19:13] [    3.297098] dracut-pre-trigger[414]: /usr/sbin/gptfix: --help                               Print this message.
[2024-11-25 07:19:13] [    3.518301]  xvda: xvda1 xvda2 xvda3
[2024-11-25 07:19:13] [    3.323297] dracut-pre-trigger[399]: //lib/dracut/hooks/pre-trigger/90-qubes_cow_setup.sh: line 80: /sys/class/block//ro: No such file or directory
```
but this is before the most recent commit

**Comment by marmarek** [comment]
But looking at the script, the current version is still broken, as it misses the "fix" parameter.

**Comment by DemiMarie** [comment]
@marmarek should I squash this?

**Comment by marmarek** [comment]
Can you resolve remaining todos from the PR description? For test I think loop device should work, I hope `--sector-size` option will be sufficient. I'd like at least have a case of already good 512, needed conversion to 4096, already good 4096 and maybe one invalid (plain ext4? truncated device?)

**Comment by marmarek** [comment]
When the tool does the conversion I get the following messages:
```
[2024-11-27 20:17:22] gptfix: Protective MBR does not cover whole disk: size in LBA is 41943039, expected 5242879
[2024-11-27 20:17:22] gptfix: Found GPT with different sector size, altering
```
Is the one about MBR size expected or a bug?

**Comment by DemiMarie** [comment]
> When the tool does the conversion I get the following messages:
> 
> ```
> [2024-11-27 20:17:22] gptfix: Protective MBR does not cover whole disk: size in LBA is 41943039, expected 5242879
> [2024-11-27 20:17:22] gptfix: Found GPT with different sector size, altering
> ```
> 
> Is the one about MBR size expected or a bug?

Expected, but if you prefer I can hide it unless `--verbose`.

**Comment by marmarek** [comment]
If it's expected then either hide it, or rephrase to not look like something went wrong.

**Comment by marmarek** [comment]
You've got duplicated commit, instead of amend.

**Comment by marmarek** [comment]
And also, your pgp key just expired.

**Comment by DemiMarie** [comment]
> And also, your pgp key just expired.

I uploaded a new one.

File: test.sh [hunk 24]
```diff
@@ -0,0 +1,29 @@
...
+
+case $0 in (/*) cd "${0%/*}/";; (*/*) cd "./${0%/*}";; (*) :;; esac
+(
+set -x
+truncate -s 0 dummy.img
+truncate -s 20GiB dummy.img
+sfdisk --force dummy.img < layout
+sfdisk --dump dummy.img > layout2
+loopdev=$(sudo losetup --nooverlap --find --sector-size 4096 --show -- dummy.img)
+trap 'sudo losetup -D -- "$loopdev"' EXIT
```
Comment (marmarek) [inline test.sh]: -D is detach-all, you want -d with specific device

File: test.sh [hunk 25]
```diff
@@ -0,0 +1,29 @@
...
+make gptfixer/gpt > /dev/null 2>&1
+sudo sfdisk --dump -- "$loopdev"
+sudo gptfixer/gpt fix "$loopdev"
+sudo sfdisk --dump -- "$loopdev"
+sudo losetup -D -- "$loopdev"
```
Comment (marmarek) [inline test.sh]: same here

File: test.sh.stderr [hunk 26]
```diff
@@ -0,0 +1,22 @@
++ truncate -s 0 dummy.img
++ truncate -s 20GiB dummy.img
++ sfdisk --force dummy.img
++ sfdisk --dump dummy.img
+++ sudo losetup --nooverlap --find --sector-size 4096 --show -- dummy.img
++ loopdev=/dev/loop0
```
Comment (marmarek) [inline test.sh.stderr]: In CI it will probably be always loop0, but not necessarily when running locally. I'm not sure how to handle it nicely (one thing is to sed expected output before comparing, but it isn't very nice). So, maybe at least print a message if you've got something else than loop0 that the failure is expected?

File: test.sh.stderr [hunk 27]
```diff
@@ -0,0 +1,22 @@
...
++ trap 'sudo losetup -D -- "$loopdev"' EXIT
++ make gptfixer/gpt
++ sudo sfdisk --dump -- /dev/loop0
+GPT PMBR size mismatch (41943039 != 5242879) will be corrected by write.
++ sudo gptfixer/gpt fix /dev/loop0
+sudo: gptfixer/gpt: command not found
```
Comment (marmarek) [inline test.sh.stderr]: This can't possibly be the expected output...

File: test.sh.stderr [hunk 28]
```diff
@@ -0,0 +1,22 @@
...
++ sudo sfdisk --dump -- /dev/loop0
+GPT PMBR size mismatch (41943039 != 5242879) will be corrected by write.
++ sudo losetup -D -- /dev/loop0
+++ sudo losetup --nooverlap --find --sector-size 512 --show -- dummy.img
++ loopdev=/dev/loop0
++ sudo sfdisk --dump -- /dev/loop0
++ sudo gptfixer/gpt -- fix /dev/loop0
+sudo: gptfixer/gpt: command not found
```
Comment (marmarek) [inline test.sh.stderr]: And here

File: test.sh.stdout [hunk 29]
```diff
@@ -0,0 +1,190 @@
...
+dummy.img33 424168 41943015 41518848 19.8G Linux filesystem
+
+The partition table has been altered.
+label: dos
+label-id: 0x00000000
+device: /dev/loop0
+unit: sectors
+sector-size: 4096
+
+/dev/loop0p1 : start=           1, size=     5242879, type=ee
```
Comment (marmarek) [inline test.sh.stdout]: This is I assume expected output when reading with mismatching sector size. Might be better to force sfdisk to look for gpt (`--label gpt`) and expect it to fail before calling the gpt fix tool.

File: layout [hunk 30]
```diff
@@ -0,0 +1,42 @@
...
+/dev/loop0p24 : start=424096,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p25 : start=424104,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p26 : start=424112,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p27 : start=424120,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p28 : start=424128,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p29 : start=424136,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p30 : start=424144,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p31 : start=424152,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
+/dev/loop0p32 : start=424160,size=8, type=00000000-0000-0000-0000-000000000000,uuid=00000000-0000-0000-0000-000000000000,name=""
```
Comment (marmarek) [inline layout]: Is there something special about those partitions to be tested? Or just a filler to see if longer GPT is handled correctly? Might want clarifying in a commit message (not sure if comments are allowed in this file?).

**Review by marmarek — CHANGES_REQUESTED** [review]
Besides specific comments below, please put those test-related files into some subdir (maybe together with gptfixer? or even gptfixer/test?) instead of the repository root.

File: layout (hunk 30 above)
Comment (DemiMarie) [reply layout]: This is a test to ensure that large partition tables are handled correctly.  It was also part of a test to ensure that the fixer would not clobber user data at the beginning or end of the volume.

File: test.sh (hunk 24 above)
Comment (DemiMarie) [reply test.sh]: Fixed.

File: test.sh (hunk 25 above)
Comment (DemiMarie) [reply test.sh]: Fixed.

File: test.sh.stderr (hunk 27 above)
Comment (DemiMarie) [reply test.sh.stderr]: yeah, that was a (rather serious) bug.

**Comment by marmarek** [comment]
you forgot to update gitlab-ci conf

**Comment by marmarek** [comment]
The test fails due to difference on "Syncing disks." line.

And also, if you extend `after_script` section in gitlab config, test coverage will be collected.

**Comment by marmarek** [comment]
There is still partition table reload in no-change case. Can this be avoided?

**Comment by marmarek** [comment]
I think it's automatic on device close, if it was opened for writing. Maybe it can be opened read-only for the checking phase?

**Comment by marmarek** [comment]
the CI test still fails

**Comment by marmarek** [comment]
> Attention: Patch coverage is `41.56118%` with `277 lines` in your changes missing coverage. Please review.

Now test coverage is properly reported :) The not covered lines are the expected ones - mostly verbose messages and various error handling. Especially, all the code that is expected to be used normally looks to be covered, so all good :)

**Comment by marmarek** [comment]
>     * [ ]  The default CFLAGS are meant for local development & debugging.

This is the only point left. Otherwise all good and tested.

**Comment by DemiMarie** [comment]
> > ```
> > * [ ]  The default CFLAGS are meant for local development & debugging.
> > ```
> 
> This is the only point left. Otherwise all good and tested.

Is it okay to keep `-Werror` on in the default build, under the assumption that anyone building without setting `CFLAGS` is doing development?  Or is that a bad assumption?

**Comment by marmarek** [comment]
> Is it okay to keep `-Werror` on in the default build, 

Yes, this is fine.

> under the assumption that anyone building without setting `CFLAGS` is doing development? Or is that a bad assumption?

This should be okay too

**Review by marmarek — APPROVED** [review]
